### ISSUE TITLE
Forbidden sign after macOS update

### ISSUE THREAD

**Issue by BenjaminOddou** [vitorgalvao/notificator#6]
Hello @vitorgalvao,

I remarked that Notificator app icon has a Forbidden Sign after a macOS update (see below)

![screen](https://user-images.githubusercontent.com/85166574/234118826-424f6ad2-d17b-4f24-98f6-5b917684f1a6.png)

Resetting manually the authorizations of all apps is working fine but maybe that's something that could be improved ?

**Comment by vitorgalvao** [comment]
Maybe it can be improved, but there are limitations to what we can do. Namely, it should continue to work without dependencies for as long as possible which means keeping the language as JXA, or possibly convert it to Swift since I could sign and notarise a binary.

Trouble is, I don’t know the exact cause and thus can’t force it to break to test different approaches. I *think* you’re right that it happens on macOS updates. *Maybe* it is fixed when the notificator is rebuilt (which happens if it’s older than 30 days, to deal with icon changes). With that in mind, one workaround would be to lower the rebuild threshold so it fixes itself sooner. Or maybe there’s an alternative solution but I can only know by testing.

First I need it to happen again and then I need to be really careful to not accidentally fix it so I figure out the ideal solution. Rest assured, I’m aware and would also like to deal with that but can’t right now (because all are working). Any extra details your or anyone else gathers in the meantime are welcome.

**Comment by vitorgalvao** [comment]
I just had one case with the forbidden sign. Poking around it seemed like the Notificator app had been rebuilt on that run so it occurred to me that maybe the cause was the rebuild itself. Perhaps overwriting the old app made macOS see some difference and add the sign.

But first I tested the idea from the previous post: does rebuilding fix it? Nope, it did not.

So let’s go the other way: reset notifications and then forcibly rebuild to see if we can reproduce the forbidden sign showing up. Nope, didn’t work either, the notification shows fine.

Then I remembered that I did install a macOS update recently. Let’s try with other notifications. Nope, they’re all fine.

Alright, then maybe it only happens after a macOS update *and* a rebuild? Nope, not that either.

Suggestions for the next batch of tests are welcome. With these I once again don’t have any notification with the forbidden sign so it’ll have to wait. I’ll keep thinking about it in the meantime.

**Comment by BenjaminOddou** [comment]
Hey @vitorgalvao with the recent macos 14.0 update, I have this little bug again. I am doing some tests, if you have some ideas to share don't hesitate !

![notif](https://github.com/vitorgalvao/notificator/assets/85166574/5f2eb4e3-6ed4-46f0-aba4-10507567914d)

**Comment by vitorgalvao** [comment]
[Apparently this a thing with other notifications](https://macmule.com/2021/10/28/notifications-showing-a-prohibitory-symbol-after-upgrading-macos-monterey/) (i.e. a macOS bug somewhere that we won’t be able to work around) and *restarting fixes it* (according to the post). Could you try that? I don’t think I did that in my tests.

**Comment by BenjaminOddou** [comment]
Indeed restarting the computer just fixed it so nothing to change.

**Comment by vitorgalvao** [comment]
At least we now know this is a macOS bug and have a known simple solution documented in this issue. Thank you for the report and checking this with me.
